---
spring:
  profiles:
    active: local
  datasource:
    url: "jdbc:mysql:replication://127.0.0.1:3306,127.0.0.1:3307,127.0.0.1:3308/work?autoReconnect=true&autoReconnectForPools=true"
    username: worker
    password: worker
    driverClassName: com.mysql.cj.jdbc.Driver
